config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

   # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
   # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
   # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

   # Defines the root path route ("/")
   root "blog_posts#index"

   resources :blog_posts do
     resource :cover_image, only: [ :destroy ], module: :blog_posts
   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_one_attached :cover_image
  has_rich_text :content
  validates :title, presence: true
  validates :content, presence: true, length: { minimum: 10 }
  scope :sorted, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/blog_posts/cover_images_controller.rb
class BlogPosts::CoverImagesController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :authenticate_user!
  before_action :set_blog_post

  def destroy
    @blog_post.cover_image.purge_later
    respond_to do |format|
      format.html { redirect_to edit_blog_post_path(@blog_post) }
      format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(@blog_post, :cover_image))  }
    end
  end

  def set_blog_post
    @blog_post = BlogPost.find(params[:blog_post_id])
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :set_post, only: [ :show, :edit, :update, :destroy ]
  def index
    @blog_posts = BlogPost.sorted
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to blog_posts_path
  end

  private
  def set_post
    @blog_post = BlogPost.find(params[:id])
  end

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :cover_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_post.html.erb
<div class="flex flex-col h-full items-center">
    <p class="mb-10">Add a new post:</p>
<%= form_with model: @blog_post do |form|%>

    <div class="flex-col justify-center items-center space-y-5 ">
        <div class = "flex flex-col">
            <%= form.label :title%>
            <%= form.text_field :title%>
            <% @blog_post.errors.full_messages_for(:title).each do |message|%>
                <%= message %>
            <%end%>
        </div>
        <% if @blog_post.cover_image.attached? %>
            <div id="<%= dom_id(@blog_post, :cover_image) %>">
                <%= image_tag @blog_post.cover_image, class: "w-1/3" %>
                <%= link_to "Remove cover image", blog_post_cover_image_path(@blog_post), data: {turbo_method: :delete} %>
            </div>
        <% end %>

         <div class = "flex flex-col">
            <%= form.label :cover_image%>
            <%= form.file_field :cover_image%>
            <% @blog_post.errors.full_messages_for(:cover_image).each do |message|%>
                <%= message %>
            <%end%>
        </div>
        
        <div>
            <%= form.rich_text_area :content%>

            <% @blog_post.errors.full_messages_for(:content).each do |message|%>
                <%= message %>
            <%end%>

        </div>
        <br>
        <div >
            <%= form.submit %>
        </div>
    </div>
</div>

<%end%>

app/views/blog_posts/edit.html.erb
EDIT
<%= render "post"%>

app/views/blog_posts/index.html.erb
<div class="w-full h-full flex justify-center">
    
        <div class="flex-col flex w-4/6  mx-20 mt-28 px-5  ">
            <% @blog_posts.each do |post|%>
            <div class = "flex-col p-5 mb-0 ">
                    <div><%= image_tag post.cover_image if post.cover_image.attached? %></div>
                    <div class="mb-3">
                        <%= link_to post.title, blog_post_path(post) %>
                    </div>
    
                     <div>
                        <%= post.content%>
                    </div>
    
            </div>
            <hr >
            <%end%>
        </div>
</div>

app/views/blog_posts/new.html.erb
<%= render "post"%>

app/views/blog_posts/show.html.erb
<div><%= image_tag @blog_post.cover_image if @blog_post.cover_image.attached? %></div>
<div><%= @blog_post.title %></div>
<div><%= @blog_post.content %></div>
<br>
<%= link_to "Home", blog_posts_path %>
<%= link_to "Edit", edit_blog_post_path %>
<%= link_to "Delete", blog_post_path, data:{turbo_method: :delete}%>

app/views/layouts/_header.html.erb
<div class="flex items-center justify-between mx-[150px] mt-[20px]">
    <div>
        <p><%= link_to "Home", root_path %></p>
        <% if user_signed_in? %>
            <p><%= link_to "New Post", new_blog_post_path %>
        <% end %>
    </div>
    <div>
        <% unless user_signed_in?%>
            <p><%= link_to "Sign In", new_user_session_path%> //  <%= link_to "Sign Up",  new_user_registration_path %></p>
        <% else %>
            <p><%= link_to "Logout", destroy_user_session_path, data:{ turbo_method: :delete}%></p>
            <p><%= link_to "Edit Profile", edit_user_registration_path %></p>
        <% end %>
    </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="w-full h-full">
  <head>
    <title><%= content_for(:title) || "Gorails Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
   <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class = "w-full h-full">
    <%= render "layouts/header"%>
    <main class="w-full h-full">
      <%= yield %>
    </main>
  </body>
</html>